name: Spring Boot CI with SonarCloud

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts/
          cd artifacts && ls

      - name: Save the artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: artifacts

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          distribution: 'sonar-scanner-cli'