name: Spring Boot CI with SonarCloud

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven Build and SonarCloud Analysis
        run: |
          mvn clean install sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=https://sonarcloud.io
          mvn -B package --file pom.xml
          mkdir -p artifacts && cp target/*.jar artifacts/
          cd artifacts && ls       

      - name: Save the artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: github-actions-artifact
          path: target/*.jar

